"""Briar Report Generator — 5 formats 📄📊📓🎨"""
import os
from datetime import datetime
from briar import __version__

class ReportGenerator:
    """Multi-format security report generator"""
    
    def __init__(self, target: str, findings: list, output_dir: str = "./reports"):
        self.target = target
        self.findings = findings
        self.output_dir = output_dir
        from urllib.parse import urlparse
        host = urlparse(target).hostname or "unknown"
        self.host_slug = host.replace(".", "-")[:40]
        self.datestr = datetime.now().strftime("%d-%m-%Y")
        self.timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        os.makedirs(output_dir, exist_ok=True)
    
    def markdown(self) -> str:
        """Generate Markdown report"""
        md = f"""# 🥀 Briar Security Audit Report

**Target:** {self.target}  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}  
**Tool:** {__version__}  
**Findings:** {len(self.findings)}

---

## 📊 Executive Summary

Briar performed an autonomous security assessment of **{self.target}**.
A total of **{len(self.findings)}** potential security issues were identified.

---

## 🔍 Findings

"""
        for i, finding in enumerate(self.findings):
            severity = finding.get("severity", "Unknown")
            emoji = {"Critical":"🔴","High":"🟠","Medium":"🟡","Low":"🟢"}.get(severity, "⚪")
            md += f"""### {emoji} Finding {i+1}: {finding.get('type', 'Vulnerability')}

**Severity:** {severity}  
**Agent:** {finding.get('agent', 'Unknown')}  
**URL:** {finding.get('url', self.target)}

{finding.get('analysis', finding.get('raw', 'No details available'))}

---
"""
        
        md += """
## 🛡️ Recommendations

1. Review all findings and prioritize by severity
2. Apply the remediation steps described in each finding
3. Re-scan after fixes are applied
4. Consider a manual penetration test for complex vulnerabilities

---
*Report generated by [Briar](https://github.com/Stiimy/briar) — Autonomous AI Pentester 🥀*
"""
        path = os.path.join(self.output_dir, f"{self.host_slug}_{self.datestr}.md")
        with open(path, "w") as f:
            f.write(md)
        return path
    
    def word(self) -> str:
        """Generate Word (.docx) report"""
        try:
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            
            doc = Document()
            
            # Title
            title = doc.add_heading(f'🥀 Briar Security Audit — {self.target}', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Meta
            doc.add_paragraph(f'Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
            doc.add_paragraph(f'Findings: {len(self.findings)}')
            doc.add_paragraph('_' * 50)
            
            # Executive Summary
            doc.add_heading('Executive Summary', level=1)
            doc.add_paragraph(
                f'Briar performed an autonomous security assessment of {self.target}. '
                f'A total of {len(self.findings)} potential security issues were identified.'
            )
            
            # Findings
            doc.add_heading('Findings', level=1)
            for i, finding in enumerate(self.findings):
                doc.add_heading(f'Finding {i+1}: {finding.get("type", "Vulnerability")}', level=2)
                
                # Severity with color
                severity = finding.get("severity", "Unknown")
                p = doc.add_paragraph()
                run = p.add_run(f'Severity: {severity}')
                if severity == "Critical":
                    run.font.color.rgb = RGBColor(255, 0, 0)
                elif severity == "High":
                    run.font.color.rgb = RGBColor(255, 128, 0)
                
                doc.add_paragraph(f'Agent: {finding.get("agent", "Unknown")}')
                doc.add_paragraph(f'URL: {finding.get("url", self.target)}')
                doc.add_paragraph(finding.get("analysis", finding.get("raw", "No details")))
                doc.add_paragraph('_' * 30)
            
            # Recommendations
            doc.add_heading('Recommendations', level=1)
            recs = [
                "Review all findings and prioritize by severity",
                "Apply the remediation steps described in each finding",
                "Re-scan after fixes are applied",
            ]
            for r in recs:
                doc.add_paragraph(r, style='List Bullet')
            
            path = os.path.join(self.output_dir, f"{self.host_slug}_{self.datestr}.docx")
            doc.save(path)
            return path
        except ImportError:
            return "⚠️ python-docx not installed. Install: pip install python-docx"
    
    def excel(self) -> str:
        """Generate Excel (.xlsx) report"""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, PatternFill, Alignment
            
            wb = Workbook()
            
            # Summary sheet
            ws1 = wb.active
            ws1.title = "Summary"
            ws1.append(["Briar Security Audit", self.target, datetime.now().isoformat()])
            ws1.append(["Total Findings", len(self.findings)])
            ws1.append([])
            ws1.append(["#", "Type", "Severity", "URL", "Agent"])
            
            for i, f in enumerate(self.findings):
                ws1.append([i+1, f.get("type","?"), f.get("severity","?"), 
                           f.get("url", self.target), f.get("agent","?")])
            
            # Details sheet
            ws2 = wb.create_sheet("Details")
            ws2.append(["#", "Full Analysis"])
            for i, f in enumerate(self.findings):
                ws2.append([i+1, f.get("analysis", f.get("raw",""))[:500]])
            
            path = os.path.join(self.output_dir, f"{self.host_slug}_{self.datestr}.xlsx")
            wb.save(path)
            return path
        except ImportError:
            return "⚠️ openpyxl not installed"
    
    def all_formats(self) -> dict:
        """Generate all available report formats"""
        return {
            "markdown": self.markdown(),
            "word": self.word(),
            "excel": self.excel(),
        }
